
spring:
#  freemarker:
#    allow-request-override: false
#    allow-session-override: false
#    cache: true
#    enabled: true
#    expose-request-attributes: false
#    expose-session-attributes: false
#    expose-spring-macro-helpers: true
#    prefer-file-system-access: true
#    suffix:  .ftl
#    template-loader-path:
#      classpath: /ftl/

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

    url: jdbc:mysql://127.0.0.1/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: false
    hibernate:
      use-new-id-generator-mappings: false
  jackson:
    default-property-inclusion: non_null
  freemarker:
    templateLoaderPath:
      classpath: /ftl
  redis:
    host: 127.0.0.1
    port: 6379



server:
  servlet:
    context-path: /sell
  port: 80
wechat:
  mpAppId: wx04217e27ba2ec8bc
  mpAppSecret: 3367f43020d819c0fb92453f0961a828
  mchId: 1500080462
  mchKey: 76172cce2a199e6d2e0c4588ac8d0e48
  keyPath: /home/apiclient_cert.p12
#  keyPath: I:\apiclient_cert.p12
  notifyUrl: http://wxin.suishouss.com/sell/pay/notify
  openAppId: 4564
  openAppSecret: fdgfdg
  templateId:
      orderStatus: N3ktkMSkwim1Scbzb4UZGAydDzLYWwxWCZvW5JsaPLU


projecturl:
  wechatMpAuthorize: http://wxin.suishouss.com
  wechatOpenAuthorize: http://wxin.suishouss.com
  sell: http://wxin.suishouss.com
  socket: wxin.suishouss.com

#projecturl:
#  wechatMpAuthorize: http://yuhao.natapp1.cc
#  wechatOpenAuthorize: http://yuhao.natapp1.cc
#  sell: http://yuhao.natapp1.cc

qiniu:
  ak: -0ZUMHORfo2SicjhTjRheY2jnAlhXBL7hl7LF7uV
  sk: ZhB2GMbWKMJfcLPpYkzbFtMWPfzONyHd1MRbQtR0
  domain: p4qg9bqm6.bkt.clouddn.com
  scheme: http